### PR TITLE
Refactor EUI64 handling.

### PR DESCRIPTION
**Pull request by Adminiuga**
Proposed changes to address #4 

Refactor `zigpy_zigate.types.EUI64` so the LSB of IEEE address is stored in the lowest list index and MSB of IEEE is in the highest list index.

### CODE REVIEW

**Comment by doudz** [comment]
Looks like it works
IEEE is not reversed
image

**Comment by doudz** [comment]
And logs are ok
```
2019-10-19 15:03:20 DEBUG (MainThread) [zigpy_zigate.zigbee.application] zigate_callback_handler [0, 0, 19, 0, 0, <Address address_mode=ADDRESS_MODE.NWK address=0xeff6>, <Address address_mode=ADDRESS_MODE.NWK address=0xfffd>, b'\xe3\xf6\xef\x8c3w\x02\x00\x8d\x15\x00\x80']
2019-10-19 15:03:20 DEBUG (MainThread) [zigpy.zdo] [0xeff6:zdo] ZDO request 0x0013: [0xeff6, 00:15:8d:00:02:77:33:8c, 128]
```

**Comment by doudz** [comment]
@Adminiuga if it looks ok for you too, I'll merge it

**Comment by Adminiuga** [comment]
Looks good. Go ahead.
Homeassistant dev was broken yesterday, so I did not push PR for zigpy
changes. I'll push it today. hA should work without it, just any zha
service calls with IEEE address would fail

**Pull request merged**
